"""Vulture whitelist - symbols that look unused but are not.

Regenerate with: make deadcode-baseline

Three kinds live here and none is dead code:
  * FastAPI route handlers, reached through decorators
  * Alembic upgrade/downgrade and revision identifiers, called by name
  * enum members and taxonomy codes that model the domain

Keeping this file current is what makes `make deadcode` worth running: a tool
that reports mostly false positives gets ignored, and then the one real finding
is ignored with it.
"""

revision  # unused variable (migrations/versions/0001_initial_schema.py:23)
down_revision  # unused variable (migrations/versions/0001_initial_schema.py:24)
branch_labels  # unused variable (migrations/versions/0001_initial_schema.py:25)
upgrade  # unused function (migrations/versions/0001_initial_schema.py:29)
downgrade  # unused function (migrations/versions/0001_initial_schema.py:156)
revision  # unused variable (migrations/versions/0002_add_investigation_outcome.py:17)
down_revision  # unused variable (migrations/versions/0002_add_investigation_outcome.py:18)
branch_labels  # unused variable (migrations/versions/0002_add_investigation_outcome.py:19)
upgrade  # unused function (migrations/versions/0002_add_investigation_outcome.py:23)
downgrade  # unused function (migrations/versions/0002_add_investigation_outcome.py:32)
_.record_replan  # unused method (src/nexus/agent/budget.py:72)
_.calls  # unused attribute (src/nexus/agent/metering.py:42)
_.calls  # unused attribute (src/nexus/agent/metering.py:70)
healthz  # unused function (src/nexus/api/routes/health.py:10)
readyz  # unused function (src/nexus/api/routes/health.py:15)
create_investigation  # unused function (src/nexus/api/routes/investigations.py:49)
list_investigations  # unused function (src/nexus/api/routes/investigations.py:212)
get_investigation  # unused function (src/nexus/api/routes/investigations.py:241)
list_evidence  # unused function (src/nexus/api/routes/investigations.py:280)
get_audit  # unused function (src/nexus/api/routes/investigations.py:292)
abort_investigation  # unused function (src/nexus/api/routes/investigations.py:323)
max_wall_clock_ms  # unused variable (src/nexus/api/schemas.py:20)
links  # unused variable (src/nexus/api/schemas.py:38)
missing_evidence  # unused variable (src/nexus/api/schemas.py:80)
evidence_count  # unused variable (src/nexus/api/schemas.py:91)
model_config  # unused variable (src/nexus/config.py:13)
redis_url  # unused variable (src/nexus/config.py:19)
retention_raw_payload_days  # unused variable (src/nexus/config.py:43)
retention_evidence_days  # unused variable (src/nexus/config.py:44)
resolved_target  # unused variable (src/nexus/db/models.py:37)
updated_at  # unused variable (src/nexus/db/models.py:50)
CursorResult  # unused import (src/nexus/db/repository.py:17)
RetentionPurge  # unused class (src/nexus/db/repository.py:163)
_.purge_expired  # unused method (src/nexus/db/repository.py:173)
_.apply_retention  # unused method (src/nexus/domain/evidence.py:35)
PLANNING  # unused variable (src/nexus/domain/models.py:12)
SYNTHESIZING  # unused variable (src/nexus/domain/models.py:14)
TERMINAL_STATUSES  # unused variable (src/nexus/domain/models.py:21)
EVENT  # unused variable (src/nexus/domain/models.py:32)
API  # unused variable (src/nexus/domain/models.py:33)
SHADOW  # unused variable (src/nexus/domain/models.py:38)
CACHED  # unused variable (src/nexus/domain/models.py:63)
STALE  # unused variable (src/nexus/domain/models.py:64)
UNKNOWN  # unused variable (src/nexus/domain/models.py:65)
PARTIAL  # unused variable (src/nexus/domain/models.py:72)
ConfidenceBand  # unused class (src/nexus/domain/models.py:75)
HIGH  # unused variable (src/nexus/domain/models.py:78)
MEDIUM  # unused variable (src/nexus/domain/models.py:79)
LOW  # unused variable (src/nexus/domain/models.py:80)
ABSTAIN  # unused variable (src/nexus/domain/models.py:81)
NON_OK_OUTCOMES  # unused variable (src/nexus/domain/models.py:94)
_.has_role  # unused method (src/nexus/domain/models.py:107)
POLICY_DECIDE  # unused variable (src/nexus/governance/audit.py:19)
DATA_ACCESS  # unused variable (src/nexus/governance/audit.py:20)
MODEL_CALL  # unused variable (src/nexus/governance/audit.py:21)
EXPORT  # unused variable (src/nexus/governance/audit.py:22)
InMemoryAuditSink  # unused class (src/nexus/governance/audit.py:52)
_.entries  # unused method (src/nexus/governance/audit.py:61)
APPROVAL_REQUIRED  # unused variable (src/nexus/governance/pdp.py:26)
WRITE  # unused variable (src/nexus/governance/pdp.py:33)
EXECUTE  # unused variable (src/nexus/governance/pdp.py:34)
ADMIN  # unused variable (src/nexus/governance/pdp.py:35)
step_seq  # unused variable (src/nexus/governance/pdp.py:47)
_nexus_error  # unused function (src/nexus/main.py:128)
InMemoryTraceSink  # unused class (src/nexus/observability/trace.py:65)
_.events  # unused method (src/nexus/observability/trace.py:72)
raw_ref  # unused variable (src/nexus/tools/contract.py:29)
required_permission  # unused variable (src/nexus/tools/contract.py:43)
_.describe  # unused method (src/nexus/tools/registry.py:27)
