"""Alembic environment (NX-030).

Two deliberate choices:

* the URL comes from NEXUS_DATABASE_URL via the application settings, so
  migrations and the service can never disagree about which database they mean,
  and no connection string is committed;
* `render_as_batch` is on so SQLite (used for local development and tests) can
  emulate the ALTER statements it does not support natively - without it, the
  first column change would pass in CI and fail on a developer machine.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from nexus.config import get_settings
from nexus.db.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Alembic's Config hands back this placeholder when the ini omits the option,
# so "unset" has to be tested for explicitly - a plain falsiness check silently
# leaves the placeholder in place and every CLI invocation then tries to connect
# to it.
_PLACEHOLDER_URL = "driver://user:pass@localhost/dbname"

# A caller may set the URL explicitly (tests do). Otherwise it comes from the
# same settings object the service uses, so the two can never disagree.
_configured = config.get_main_option("sqlalchemy.url", None)
if not _configured or _configured == _PLACEHOLDER_URL:
    config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata


def _configure(connection: Connection | None = None, url: str | None = None) -> None:
    context.configure(
        connection=connection,
        url=url,
        target_metadata=target_metadata,
        literal_binds=url is not None,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        render_as_batch=True,
    )


def run_migrations_offline() -> None:
    _configure(url=config.get_main_option("sqlalchemy.url"))
    with context.begin_transaction():
        context.run_migrations()


#: Tables that only revision 0001 creates. If they exist while Alembic thinks
#: the database is empty, the database predates the migration chain.
_OWNED_TABLES = frozenset({"investigation", "evidence", "trace_step", "audit_record"})


#: Commands that read, or that exist precisely to repair an unversioned
#: database. Guarding these would block the recovery the guard recommends.
_UNGUARDED_COMMANDS = frozenset({"stamp", "current", "history", "heads", "branches", "show"})


def _guard_applies() -> bool:
    if context.get_x_argument(as_dictionary=True).get("allow_unversioned") == "true":
        return False
    cmd = getattr(getattr(config, "cmd_opts", None), "cmd", None)
    if cmd and getattr(cmd[0], "__name__", "") in _UNGUARDED_COMMANDS:
        return False
    return True


def _guard_unversioned_schema(connection: Connection) -> None:
    """Fail readably when a database predates the migration chain.

    Without this, Alembic decides the database is empty, replays 0001, and dies
    on "table already exists" inside a hundred lines of traceback that never
    mention the actual problem.
    """
    from sqlalchemy import inspect, text

    if not _guard_applies():
        return

    tables = set(inspect(connection).get_table_names())

    existing = _OWNED_TABLES & tables
    if not existing:
        return  # genuinely empty - a normal first migration

    if "alembic_version" in tables:
        # Read the table directly. Building a second MigrationContext inside an
        # in-progress Alembic run reports no revision even when one is recorded.
        stamped = connection.execute(text("select version_num from alembic_version")).first()
        if stamped is not None:
            return  # already versioned - nothing to warn about

    raise RuntimeError(
        "This database already contains "
        + ", ".join(sorted(existing))
        + " but carries no Alembic revision, so it predates the migration "
        "chain (it was built by the old create_all path, or a revision was "
        "autogenerated against it without stamping).\n\n"
        "If the data is disposable - a local dev database usually is - delete "
        "it and migrate from scratch.\n"
        "To keep it, tell Alembic which revision the schema already matches:\n"
        "    uv run alembic stamp 0001\n"
        "    uv run alembic upgrade head\n"
        "Check the schema really does match 0001 before stamping; stamping the "
        "wrong revision leaves the database silently inconsistent.\n\n"
        "To bypass this check deliberately: -x allow_unversioned=true"
    )


def do_run_migrations(connection: Connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    # The guard runs on its own connection and that connection is closed before
    # the migration one opens. Querying the migration connection first starts an
    # implicit transaction, which turns Alembic's own begin_transaction() into a
    # nested no-op - migrations then report success while committing nothing.
    async with connectable.connect() as connection:
        await connection.run_sync(_guard_unversioned_schema)

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
