"""Initial schema: investigation, evidence, trace_step, audit_record.

Every table carries tenant_id as the leading column of its composite indexes
(ADR-10), and every table holding retrievable content carries expires_at so the
retention purge has something to act on (ADR-11).

On PostgreSQL this revision also makes audit_record append-only for the
application role (NX-022). See migrations/README.

Revision ID: 0001
Revises:
Create Date: 2026-09-07 14:21:01.862650

"""

import os
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_record",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=36), nullable=True),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("resource", sa.String(length=512), nullable=False),
        sa.Column("purpose", sa.String(length=128), nullable=False),
        sa.Column("policy_id", sa.String(length=128), nullable=True),
        sa.Column("decision", sa.String(length=24), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("result_status", sa.String(length=32), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_record", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_tenant_investigation", ["tenant_id", "investigation_id"], unique=False
        )
        batch_op.create_index(
            "ix_audit_tenant_occurred", ["tenant_id", "occurred_at"], unique=False
        )

    op.create_table(
        "investigation",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=True),
        sa.Column("resolved_target", sa.JSON(), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("policy_version", sa.String(length=64), nullable=True),
        sa.Column("budget", sa.JSON(), nullable=True),
        sa.Column("consumed", sa.JSON(), nullable=True),
        sa.Column("failure_code", sa.String(length=48), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("investigation", schema=None) as batch_op:
        batch_op.create_index("ix_investigation_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_investigation_tenant_created", ["tenant_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_investigation_tenant_subject", ["tenant_id", "subject_id"], unique=False
        )

    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=36), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_resource_id", sa.String(length=512), nullable=False),
        sa.Column("evidence_type", sa.String(length=64), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("freshness", sa.String(length=16), nullable=False),
        sa.Column("sensitivity", sa.String(length=16), nullable=False),
        sa.Column("integrity", sa.String(length=16), nullable=False),
        sa.Column("authz_context", sa.JSON(), nullable=True),
        sa.Column("content_ref", sa.String(length=512), nullable=True),
        sa.Column("content_summary", sa.Text(), nullable=True),
        sa.Column("citation_key", sa.String(length=32), nullable=False),
        sa.Column("redaction_applied", sa.JSON(), nullable=True),
        sa.Column("retention_class", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index("ix_evidence_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_evidence_tenant_investigation", ["tenant_id", "investigation_id"], unique=False
        )

    op.create_table(
        "trace_step",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("investigation_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.String(length=32), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=True),
        sa.Column("policy_decision_id", sa.String(length=36), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=True),
        sa.Column("error_class", sa.String(length=48), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("trace_step", schema=None) as batch_op:
        batch_op.create_index("ix_trace_expires", ["expires_at"], unique=False)
        batch_op.create_index(
            "ix_trace_tenant_investigation_seq",
            ["tenant_id", "investigation_id", "seq"],
            unique=False,
        )

    # ### end Alembic commands ###
    _set_audit_append_only(enabled=True)


def downgrade() -> None:
    """Downgrade schema."""
    _set_audit_append_only(enabled=False)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trace_step", schema=None) as batch_op:
        batch_op.drop_index("ix_trace_tenant_investigation_seq")
        batch_op.drop_index("ix_trace_expires")

    op.drop_table("trace_step")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_evidence_tenant_investigation")
        batch_op.drop_index("ix_evidence_expires")

    op.drop_table("evidence")
    with op.batch_alter_table("investigation", schema=None) as batch_op:
        batch_op.drop_index("ix_investigation_tenant_subject")
        batch_op.drop_index("ix_investigation_tenant_created")
        batch_op.drop_index("ix_investigation_expires")

    op.drop_table("investigation")
    with op.batch_alter_table("audit_record", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_tenant_occurred")
        batch_op.drop_index("ix_audit_tenant_investigation")

    op.drop_table("audit_record")
    # ### end Alembic commands ###


def _set_audit_append_only(*, enabled: bool) -> None:
    """Give the application role least privilege, and make audit_record
    append-only for it (NX-022).

    A REVOKE alone is not enough. PostgreSQL lets a superuser, and the owner of
    a table, bypass the ACL entirely - so a role that is either will still be
    able to update and delete audit rows while pg_class.relacl shows the
    privilege withdrawn. That is worse than no control, because it reads as one.
    This function therefore refuses to run against such a role.

    The application role is expected to exist already; deployed environments
    create it alongside the database, and local development creates it in
    deploy/postgres-init. SQLite has no privilege system and is skipped.
    """
    # get_context().dialect is correct in both online and offline modes;
    # get_bind() is not populated when rendering static SQL.
    if op.get_context().dialect.name != "postgresql":
        return

    role = os.environ.get("NEXUS_DB_APP_ROLE", "nexus_app")
    if not role.replace("_", "").isalnum():
        raise ValueError(f"NEXUS_DB_APP_ROLE {role!r} is not a plain identifier")

    if op.get_context().as_sql:
        # Static SQL rendering has no connection to interrogate, so emit the
        # statements and leave the superuser check to the live run.
        _emit_grants(role, enabled=enabled)
        return

    bind = op.get_bind()
    exists, is_super = bind.execute(
        sa.text("select true, rolsuper from pg_roles where rolname = :r"),
        {"r": role},
    ).first() or (False, False)
    if not exists:
        raise RuntimeError(
            f"application role {role!r} does not exist. Create it before "
            "migrating; see deploy/postgres-init/01-app-role.sql."
        )
    if is_super:
        raise RuntimeError(
            f"application role {role!r} is a superuser, which bypasses table "
            "ACLs. The append-only guarantee on audit_record would be vacuous. "
            "Point NEXUS_DB_APP_ROLE at a non-superuser role that does not own "
            "these tables."
        )
    owners = (
        bind.execute(sa.text("select tableowner from pg_tables where tablename = 'audit_record'"))
        .scalars()
        .all()
    )
    if role in owners:
        raise RuntimeError(
            f"application role {role!r} owns audit_record; an owner bypasses "
            "the ACL. Migrations should run as a separate owner role."
        )

    _emit_grants(role, enabled=enabled)


def _emit_grants(role: str, *, enabled: bool) -> None:
    data_tables = "investigation, evidence, trace_step"
    if enabled:
        op.execute(f'GRANT SELECT, INSERT, UPDATE, DELETE ON {data_tables} TO "{role}"')
        op.execute(f'GRANT SELECT, INSERT ON audit_record TO "{role}"')
        # Belt and braces: explicit even though the GRANT above omits them.
        op.execute(f'REVOKE UPDATE, DELETE ON audit_record FROM "{role}"')
    else:
        op.execute(f'REVOKE ALL ON {data_tables} FROM "{role}"')
        op.execute(f'REVOKE ALL ON audit_record FROM "{role}"')
