"""add investigation.outcome

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-08 10:23:27.957664

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("investigation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("outcome", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the change. Every revision must implement this (NX-030)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("investigation", schema=None) as batch_op:
        batch_op.drop_column("outcome")

    # ### end Alembic commands ###
